Enhancement: Implement VersionOrConstraintNormalizer
ergebnis/composer-normalize pull request #18
Opened 2018-01-15 21:16 UTC by localheinz

This PR

* [x] implements a `VersionOrConstraintNormalizer`

Fixes #16.

💁‍♂️ Not sure, maybe it could handle even more than just the or constraints. For example, trimming between version constraints (ensuring a single space between them) sounds good to me, too. 

What do you think, @Soullivaneuh?

2018-01-15 22:03 UTC, Soullivaneuh commented
> For example, trimming between version constraints

Yeah!

> ensuring a single space between them

Looks good, but maybe we should find official examples on getcomposer.org

2018-01-15 22:05 UTC, Soullivaneuh commented
I can't find official example, but I always see something like `^2.0,<=2.0.4` without any space. So it should be ok.

2018-01-16 11:24 UTC, soullivaneuh requested changes

2018-01-16 11:24 UTC, Soullivaneuh commented on README.md
> +sections, the `VersionOrConstraintNormalizer` will ensure that a `||` is
` || ` (with spaces around)

2018-01-18 22:33 UTC, localheinz commented
@Soullivaneuh 

Would you like to take another look?

2018-01-19 22:24 UTC, localheinz commented
@Soullivaneuh 

I incorporated all examples I could find at https://getcomposer.org/doc/articles/versions.md and think of, I think this is good to merge (once the build has passed).

2018-01-19 22:38 UTC, merged

2018-01-23 11:18 UTC, Soullivaneuh commented
Sorry for the delay, but it looks great!

2018-01-23 15:06 UTC, localheinz commented
Glad you like it, @Soullivaneuh!